version: '3'
services:
  puppet:
    hostname: puppet
    image: puppet/puppetserver
    ports:
      - 8140:8140
    environment:
      - DNS_ALT_NAMES=puppet,localhost,127.0.0.1,${DNS_ALT_NAMES:-}
      - PUPPETDB_SERVER_URLS=https://puppetdb:8081
    volumes:
      - ./volumes/code:/etc/puppetlabs/code/
      - ./volumes/puppet:/etc/puppetlabs/puppet/
      - ./volumes/serverdata:/opt/puppetlabs/server/data/puppetserver/
    networks:
      default:

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
      - POSTGRES_DB=puppetdb
    expose:
      - 5432
    volumes:
      - ./volumes/puppetdb-postgres/data:/var/lib/postgresql/data/
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      default:

  puppetdb:
    hostname: puppetdb
    image: puppet/puppetdb
    environment:
      - PUPPETDB_PASSWORD=puppetdb
      - PUPPETDB_USER=puppetdb
    ports:
      - 8080
      - 8081
    depends_on:
      - postgres
      - puppet
    volumes:
      - ./volumes/puppetdb/ssl:/etc/puppetlabs/puppet/ssl/
    networks:
      default:
  
  # agent will exit 0 after run
  agent:
    container_name: agent
    # change the hostname to get different 
    # puppet roles assigned
    hostname: agent
    image: puppet/puppet-agent
    networks:
      default:

networks:
  default:
